name: Update Submodules
on:
  schedule:
    - cron: '*/15 * * * *'

permissions: write-all

jobs:

  Update-Submodules:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Pull down submodules
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
  
          git submodule update --init --recursive --remote
  
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update Pelican Submodule"
            git push
          else
            echo "no changes";
          fi
